name: Docker Image CI
on:
  # Trigger the workflow on push
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repository
      - name: Checking out the repository
        uses: actions/checkout@v2
       
      # Setting up Docker Builder
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_UN }}
          password: ${{ secrets.GHCR_AUTH}}
          
      # Push to Github Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: latest
          file: ./User/Server/Dockerfile
          push: true
          tags: ghcr.io/mervegunak/image_name:latest
